from enum import Enum

# Based on Project Tuning framework https://tuningacademy.org/competences/generic-competences-tuning-la-i-and-ii/
class Competence(str, Enum):
    CMP_01 = "Capacity for abstraction, analysis, and synthesis"
    CMP_02 = "Ability to apply knowledge in practice"
    CMP_03 = "Ability to organise and plan time"
    CMP_04 = "Knowledge regarding the area of study and related professions"
    CMP_05 = "Social responsibility and commitment to citizenship"
    CMP_06 = "Capacity for oral and written communication"
    CMP_07 = "Ability to communicate in a second language"
    CMP_08 = "Ability to use information and communication technology"
    CMP_09 = "Capacity for investigation"
    CMP_10 = "Ability to learn and update learning"
    CMP_11 = "Ability to search for, process, and analyse information from a variety of sources"
    CMP_12 = "Critical and self-critical abilities"
    CMP_13 = "Ability to react to new situations"
    CMP_14 = "Creative skills"
    CMP_15 = "Ability to identify, pose, and solve problems"
    CMP_16 = "Ability to make decisions"
    CMP_17 = "Ability to work as part of a team"
    CMP_18 = "Interpersonal skills"
    CMP_19 = "Ability to motivate and work towards common goals"
    CMP_20 = "Commitment to look after the environment"
    CMP_21 = "Commitment to socio-cultural environment"
    CMP_22 = "Value and respect for diversity and multiculturality"
    CMP_23 = "Ability to work in international contexts"
    CMP_24 = "Ability to work autonomously"
    CMP_25 = "Ability to formulate and manage projects"
    CMP_26 = "Ethical commitment"
    CMP_27 = "Commitment to quality"

class Industry(str, Enum):
    IND_01 = "Technology/IT"
    IND_02 = "Healthcare"
    IND_03 = "Finance/Banking"
    IND_04 = "Manufacturing"
    IND_05 = "Retail/Consumer Goods"
    IND_06 = "Energy/Utilities"
    IND_07 = "Telecommunications"
    IND_08 = "Transportation/Logistics"
    IND_09 = "Education"
    IND_10 = "Government/Public Sector"
    IND_11 = "Hospitality/Tourism"
    IND_12 = "Real Estate/Construction"
    IND_13 = "Media/Entertainment"

class ResponsibilityLevel(Enum):
    RSP_01 = "Operational"
    RSP_02 = "Tactical"
    RSP_03 = "Strategic"

class Profession(Enum):
    PRF_01 = "Engineering"
    PRF_02 = "Medicine"
    PRF_03 = "Finance"
    PRF_04 = "Marketing"
    PRF_05 = "Sales"
    PRF_06 = "Human Resources"
    PRF_07 = "Technology"
    PRF_08 = "Education"
    PRF_09 = "Legal"
    PRF_10 = "Consulting"
    PRF_11 = "Construction"
    PRF_12 = "Design"
    PRF_13 = "Hospitality"
    PRF_14 = "Science & Research"
    PRF_15 = "Supply Chain & Logistics"
    PRF_16 = "Public Administration"
    PRF_17 = "Journalism & Media"
    PRF_18 = "Customer Service"

class ExperienceLevel(Enum):
    EXP_01 = "Entry Level"
    EXP_02 = "Mid Level"
    EXP_03 = "Senior Level"
    EXP_04 = "Executive"

class SpecializationArea(Enum):
    SPC_01 = "Mechanical Engineering"
    SPC_02 = "Electrical Engineering"
    SPC_03 = "Industrial Engineering"
    SPC_04 = "Robotics"
    SPC_05 = "General Practice"
    SPC_06 = "Cardiology"
    SPC_07 = "Orthopedics"
    SPC_08 = "Pulmonology"
    SPC_09 = "Surgery"
    SPC_10 = "Psychology"
    SPC_11 = "Laboratory Analysis"
    SPC_12 = "Accounting"
    SPC_13 = "Risk Management"
    SPC_14 = "Taxation"
    SPC_15 = "Auditing"
    SPC_16 = "Digital Marketing"
    SPC_17 = "Brand Management"
    SPC_18 = "Market Research"
    SPC_19 = "Advertising"
    SPC_20 = "Public Relations"
    SPC_21 = "Influencer Marketing"
    SPC_22 = "B2B Sales"
    SPC_23 = "B2C Sales"
    SPC_24 = "Key Account Management"
    SPC_25 = "Recruitment"
    SPC_26 = "Talent Management"
    SPC_27 = "Organizational Development"
    SPC_28 = "Workplace Safety"
    SPC_29 = "Software Development"
    SPC_30 = "Data Science"
    SPC_31 = "Cybersecurity"
    SPC_32 = "Cloud Computing"
    SPC_33 = "Database Administration"
    SPC_34 = "Artificial Intelligence & Machine Learning"
    SPC_35 = "IT Support"
    SPC_36 = "Web Development"
    SPC_37 = "School Education"
    SPC_38 = "Higher Education"
    SPC_39 = "Special Education"
    SPC_40 = "Online Education"
    SPC_41 = "Corporate Law"
    SPC_42 = "Criminal Law"
    SPC_43 = "Family Law"
    SPC_44 = "Business Strategy"
    SPC_45 = "Project Management"
    SPC_46 = "Operations Consulting"
    SPC_47 = "Supply Chain"
    SPC_48 = "Procurement"
    SPC_49 = "Architecture"
    SPC_50 = "Urban Planning"
    SPC_51 = "Construction"
    SPC_52 = "Electrical Installation"
    SPC_53 = "Policy Analysis"
    SPC_54 = "Social Services"
    SPC_55 = "Transportation Planning"

class OrganizationalCulture(Enum):
    ORG_01 = "Innovative"
    ORG_02 = "Customer-Centric"
    ORG_03 = "Collaborative"
    ORG_04 = "Inclusive"
    ORG_05 = "Ethical"
    ORG_06 = "Flexible"
    ORG_07 = "Learning-Oriented"
    ORG_08 = "Performance-Oriented"
    ORG_09 = "Employee-Centric"
    ORG_10 = "Purpose-Driven"
    ORG_11 = "Competitive"
    ORG_12 = "Risk-Taking"
    ORG_13 = "Community-Oriented"
    ORG_14 = "Sustainability-Focused"
    ORG_15 = "Data-Driven"
    ORG_16 = "Fast-Paced"
    ORG_17 = "Entrepreneurial"
    ORG_18 = "Trust-Based"